version: "3"
services:
  postgres:
    image: postgres
    ports:
      - 5432
  rails:
    container_name: tubatuba
    build: .
    volumes:
      - .:/tubatuba
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    links:
      - postgres
    command: sh entrypoint-dev.sh
  redis:
    image: redis
    command: redis-server --appendonly yes
  resque:
    build: .
    volumes:
      - .:/tubatuba
    environment: 
      - RAILS_ENV=development
      - QUEUE=*
    command: rake resque:work
    links: 
      - postgres